### ISSUE TITLE
Distillery and included_applications

### ISSUE THREAD

**Issue by bismark** [ericentin/exexec#10]
It appears to me that included `erlexec` in the `included_applications` list causes some issues when building a release with Distillery.

https://github.com/ericentin/exexec/blob/1828403bd657a9f3fc0b55926bf7c34395921a11/mix.exs#L32

This is interesting because it highlights a behavior in `mix` that's different from a release.

If `:erlexec` is in the `extra_applications` `mix` config, `erlexec` will always be started by `mix`, i.e. overriding `exexec`'s `included_application` setting. However, the release will ignore `extra_applications` and expects `exexec` to start `erlexec`, which it never does, so `erlexec` is never started.

For a concrete example with `erlexec` set in `extra_applications`:

Here are the relevant `.app` files:

`example.app`:

```
{application,example,
             [{applications,[kernel,stdlib,elixir,logger,erlexec,exexec,
                             distillery]},
              {description,"example"},
              {modules,['Elixir.Example','Elixir.Example.Application']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.Example.Application',[]}}]}.
```

`exexec.app`:

```
{application,exexec,
             [{applications,[kernel,stdlib,elixir]},
              {description,"An idiomatic Elixir wrapper for erlexec."},
              {modules,['Elixir.Exexec','Elixir.Exexec.ToErl']},
              {registered,[]},
              {vsn,"0.2.0"},
              {included_applications,[erlexec]}]}.
```

Running with mix:

```
$ iex -S mix
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Application.started_applications() |> Enum.find(&match?({:erlexec,_,_}, &1))
{:erlexec, 'OS Process Manager', '1.9.5'}
```

Running with a Distillery release:

```
_build/dev/rel/example/bin/example console
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(example@127.0.0.1)1> Application.started_applications() |> Enum.find(&match?({:erlexec,_,_}, &1))
nil
```

I wanted to document this for future reference and in case someone else comes across this issue, but I think it's also worth asking the question why does `exexec` include `erlexec` as an `included_application` without explicitly starting it?

**Comment by ericentin** [comment]
Should no longer be an issue. Thanks.
