### ISSUE TITLE
Including exexec as a dependency in a Phoenix app that runs as root causes app to crash

### ISSUE THREAD

**Issue by hiway** [ericentin/exexec#14]
Thank you for this library.

I'm new to Elixir and am building a tool to manage my FreeBSD jails. It needs to run as root to access all the required files and have permission to create and run jails, I am aware of the risks and want to override them for building a prototype. 

I added exexec as a dependency with no other change, built and deployed the application and it promptly crashed with this error message:

```
Not allowed to run as root without setting effective user (-user option)! [c_src/exec.cpp:539]
10:32:53.966 [info] Application erlexec exited: :exec_app.start(:normal, []) returned an error: shutdown: failed to start child: :exec
    ** (EXIT) {:port_exited_with_status, 4}
...
```

I have not accessed the library in any way, had no opportunity to set any options.
I am unsure where am I supposed to set the options mentioned here:

https://saleyn.github.io/erlexec/overview-summary.html

Under:  Running the port program as root

How should I pass the options via exexec to pacify erlexec about running as root?

**Comment by ericentin** [comment]
Hi. Unfortunately I don't provide support. Your problem lies outside of exexec, though. Good luck.
